### ISSUE TITLE
.7z Unix

### ISSUE THREAD

**Issue by ZestyTS** [ZestyTS/RetroManager#3]
Add support on CompressRoms to allow .7z compression.

**Comment by jereddowden** [comment]
This can be handled by p7zip. Its a third-party port of 7zip. Same commands work and everything. Problem is, it doesn't come installed on most unix distros and macs. Is there a way we could bundle it as a dependency on unix systems?

**Comment by ZestyTS** [comment]
We could also look around for 7z-dlls to just add into the project, but that would also require a lot of code changes.

Depending on which way we go, #4 might be affected.

**Comment by jereddowden** [comment]
So this is handled in the compressionChanges branch. The new implementation just needs to be tested on Windows and Linux.

**Comment by jereddowden** [comment]
This has been tested, and works in 3e452aa812cd8c9a89a7831d3f84fbf71b43ff2a
